Feature/admin
llss1989/taskmanager pull request #12
Opened 2022-11-02 09:18 UTC by llss1989

2022-11-02 15:12 UTC, greybutton requested changes
1 в коммитах не надо смешивать язык, пиши на английском
2 снова файлы поменялись. в прошлый раз я пропустил, сейчас не пропущу, пока не объяснишь причину

2022-11-02 15:12 UTC, greybutton commented on app/views/admin/users/_form-user.html.slim
> += simple_form_for @user, as: :user, url: current_url do |f|
app/views/admin/users/_form.html.slim

2022-11-02 15:12 UTC, greybutton commented on app/views/admin/users/_form-user.html.slim
> +  h4=title
можно убрать в edit/new и не передавать как параметр

2022-11-02 16:52 UTC, llss1989 commented on app/views/admin/users/_form-user.html.slim
> += simple_form_for @user, as: :user, url: current_url do |f|
1. ок.
2. Не сразу понял о чем речь идет. Я репозитории бывает меняю, делаю мерж и иду дальше (в прошлый раз три PR было на проверке).потом второй раз уже по быстрее получается и лучше запомню, так было в прошлый раз. Один раз я в гите запутался. Не знал что так нельзя, ведь делаю полный клон репо и он линкуется с гитом. Теперь буду знать.

2022-11-02 17:04 UTC, llss1989 commented on app/views/admin/users/_form-user.html.slim
> += simple_form_for @user, as: :user, url: current_url do |f|
+ переустанавливал убунту потому что yarn для 20 версии убунту нету.

2022-11-02 18:10 UTC, llss1989 commented
> 1 в коммитах не надо смешивать язык, пиши на английском 2 снова файлы поменялись. в прошлый раз я пропустил, сейчас не пропущу, пока не объяснишь причину



> 1 в коммитах не надо смешивать язык, пиши на английском 2 снова файлы поменялись. в прошлый раз я пропустил, сейчас не пропущу, пока не объяснишь причину

2022-11-02 18:15 UTC, llss1989 commented
> 1 в коммитах не надо смешивать язык, пиши на английском 2 снова файлы поменялись. в прошлый раз я пропустил, сейчас не пропущу, пока не объяснишь причину

1.ok
2.Пробывал восстановить последовательность изменений, не хотел ошибиться в отступах. Впредь буду пользоваться дифом чтобы изменения были в местах, про которые и идет речь в PR.

2022-11-02 18:20 UTC, llss1989 commented on app/views/admin/users/_form-user.html.slim
> += simple_form_for @user, as: :user, url: current_url do |f|
1.ok
2.Пробывал восстановить последовательность изменений, не хотел ошибиться в отступах. Впредь буду пользоваться дифом чтобы изменения были в местах, про которые и идет речь в PR.

2022-11-03 04:28 UTC, llss1989 commented
> 1 в коммитах не надо смешивать язык, пиши на английском 2 снова файлы поменялись. в прошлый раз я пропустил, сейчас не пропущу, пока не объяснишь причину
1.ok
2.Пробывал восстановить последовательность изменений, не хотел ошибиться в отступах. Впредь буду пользоваться дифом чтобы изменения были в местах, про которые и идет речь в PR.

2022-11-03 04:28 UTC, llss1989 commented on app/views/admin/users/_form-user.html.slim
> += simple_form_for @user, as: :user, url: current_url do |f|
1.ok
2.Пробывал восстановить последовательность изменений, не хотел ошибиться в отступах. Впредь буду пользоваться дифом чтобы изменения были в местах, про которые и идет речь в PR.

2022-11-03 05:07 UTC, greybutton requested changes
1 файл так и остался app/views/admin/users/_form-user.html.slim, надо было переименовать
2 почему файлы то меняются, но изменений нет?

2022-11-03 05:36 UTC, llss1989 commented
> 1 файл так и остался app/views/admin/users/_form-user.html.slim, надо было переименовать 2 почему файлы то меняются, но изменений нет?
1.Название файла переделать  в _form_user.html.slim?
2. Один раз я переустанавливал ubuntu (переходил с 20 на 18), один раз решил не ждать проверки PR, их было три и сделал наперед, а все незаппрувленные ветки смержил, там наверно и поменялось репо...

2022-11-03 17:45 UTC, greybutton requested changes
чот объяснение непонятное. причем здесь переустановка убунты, про репо не понял что менял 

даже если клонировал репо заново, то что изменилось в app/controllers/web/developers_controller.rb например? что дифф показывал? 

у тебя странные вещи какие то происходят, файлы меняются, но изменений нет)

2022-11-03 17:45 UTC, greybutton commented on app/views/admin/users/_form_user.html.slim
> += simple_form_for @user, as: :user, url: current_url do |f|
здесь писал как файл должен называться https://github.com/llss1989/taskmanager/pull/12#discussion_r1011914499

2022-11-03 18:33 UTC, llss1989 commented on app/views/admin/users/_form_user.html.slim
> += simple_form_for @user, as: :user, url: current_url do |f|
Только сейчас увидел о чем речь идет, git дописывает emptyfile, так вроде файлы и не empty и они только в изменениях чтоли видны, расширения файлов и содержание на месте, а видны они только в гите, надо гуглить и смотреть что это.

2022-11-06 12:05 UTC, greybutton approved these changes

2022-11-06 14:06 UTC, merged