Feature/assignee
llss1989/taskmanager pull request #17
Opened 2022-11-23 17:32 UTC by llss1989

2022-11-24 06:30 UTC, greybutton requested changes
в TaskBoard тоже презентер нужен для тасок

2022-11-24 06:30 UTC, greybutton commented on app/javascript/components/EditPopup/Form/Form.js
> +import UserSelect from 'components/UserSelect/UserSelect';
from 'components/UserSelect';

2022-11-24 06:30 UTC, greybutton commented on app/javascript/components/EditPopup/EditPopup.js
> +          title={isLoading ? 'Your task is loading. Please be patient.' : `Task # ${task.id} [${TaskPresenter.name(task)}]`}
id тоже через презентер

2022-11-24 06:30 UTC, greybutton commented on app/javascript/components/EditPopup/Form/Form.js
> +        value={TaskPresenter.name(task)}
description тоже через презентер

2022-11-24 15:11 UTC, greybutton requested changes
> @llss1989
[Merge branch 'feature/assignee' of](https://github.com/llss1989/taskmanager/pull/17/commits/e64eee8801c00f47230305fb514446b92f7c0bc8)

отребейзи от родительской ветки, чтобы не было таких коммитов

2022-11-24 18:49 UTC, greybutton requested changes
коммит про который писал не исчез, и добавился [merge feature/tasks in feature/assignee](https://github.com/llss1989/taskmanager/pull/17/commits/1982c11b2403a12a41e69f12fdf5fa796841505e)

не знаю что ты сделал, но что то явно не то) тебе надо feature/assignee отребейзить от feature/tasks

2022-11-24 20:54 UTC, llss1989 commented
> коммит про который писал не исчез, и добавился [merge feature/tasks in feature/assignee](https://github.com/llss1989/taskmanager/pull/17/commits/1982c11b2403a12a41e69f12fdf5fa796841505e)
> 
> не знаю что ты сделал, но что то явно не то) тебе надо feature/assignee отребейзить от feature/tasks

чет я запутался с этим ребейсом, до этого пробывал git rebase feature/tasks, гит потребовал решить конфликты и после замержить, после посмотрел gitlog не увидел мержи и радостно запушил.

2022-11-25 10:25 UTC, greybutton approved these changes

2022-11-25 16:38 UTC, merged