Feature/coveralls test
llss1989/taskmanager pull request #21
Opened 2022-11-30 09:31 UTC by llss1989

2022-11-30 18:24 UTC, greybutton requested changes

2022-11-30 18:24 UTC, greybutton commented on test/test_helper.rb
> +  if ENV['COVERAGE']
покрытие лучше генерировать только если тесты через CI запущены, иначе всегда будут генерироваться на запуск тестов, а всегда не нужно. Не уверен, что этот код так работает

2022-11-30 19:08 UTC, llss1989 commented on test/test_helper.rb
> +  if ENV['COVERAGE']
если поменять на ENV['CI'] получаю ошибку Lcov file not found.  Получилось ее обойти при помощи ENV['COVERAGE'].

2022-12-01 05:40 UTC, greybutton commented on test/test_helper.rb
> +  if ENV['COVERAGE']
я имел в виду не имя энв переменной, а где иф стоит

2022-12-01 08:39 UTC, greybutton approved these changes

2022-12-01 08:39 UTC, greybutton commented on README.md
> +[![Coverage Status](https://coveralls.io/repos/github/llss1989/taskmanager/badge.svg?branch=feature/coverallsTest)](https://coveralls.io/github/llss1989/taskmanager?branch=feature/coverallsTest)
лучше на девелоп ветку настроить бейдж

2022-12-01 09:19 UTC, merged