Added step sessions
llss1989/taskmanager pull request #8
Opened 2022-10-28 08:51 UTC by llss1989

2022-10-28 17:31 UTC, greybutton requested changes
> This branch has conflicts that must be resolved

надо порешать конфликты перед тем как на проверку отправлять

2022-10-28 17:31 UTC, greybutton commented on app/views/web/sessions/new.html.slim
>  p Find me in app/views/web/sessions/new.html.slim
это удалить можно

2022-10-28 18:39 UTC, llss1989 commented
> > This branch has conflicts that must be resolved
> 
> надо порешать конфликты перед тем как на проверку отправлять

2022-10-29 19:13 UTC, greybutton approved these changes

2022-10-31 06:19 UTC, merged